version: '3'
services:
  taxgpt-backend:
    build: .
    command: uvicorn core.asgi:application --host 0.0.0.0 --port 8000 --lifespan off
    volumes:
      - .:/app
      - ./staticfiles:/staticfiles
    ports:
      - "8000:8000"
  celery-worker:
    build: .
    command: celery -A core worker --loglevel=info -c 4  # Adjust the number of workers (4 in this example)
    volumes:
      - .:/app
    depends_on:
      - taxgpt-backend

